### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by Chocobo1**
Now I actually need to install this project as a package, so I whipped up a setup.py.
Not sure you'll like it though, since it moves files around.

ps. Please consider merge PR #11 before this one.
pps. You haven't specified a license for this project, do you consider adding one? I've left `license` field empty (in setup.py) for now.

### CODE REVIEW

**Comment by ebattenberg** [comment]
Moving stuff around is fine as long as it still works.  Having a package seems preferable to me, since it makes it easier to use and install for everyone.  This LGTM, but merging #11 has created some conflicts.

**Comment by ebattenberg** [comment]
I just added a LICENSE file (MIT).

**Comment by Chocobo1** [comment]
Conflicts resolved.

>Moving stuff around is fine as long as it still works.

Yep and nosetests still works.

>I just added a LICENSE file (MIT).

Nice! I've updated the license field in setup.py.

**Comment by ebattenberg** [comment]
Thanks a lot!

**Pull request merged**
